Repository uselagoon/lagoon-charts, pull requests merged in 2024-02, with the labels that each got.

#642 CDN service annotation support
  README.md
  charts/lagoon-logging/Chart.yaml
  charts/lagoon-logging/ci/linter-values.yaml
  charts/lagoon-logging/templates/cdn-logs-collector.service.yaml
  charts/lagoon-logging/templates/tests/cdn-service-annotations.yaml
  charts/lagoon-logging/values.yaml
Labels: lagoon-logging

#638 fix: avoid installing the registry multiple times
  Makefile
Labels: ci

#619 chore: modify keycloak healthcheck endpoint for newer keycloak
  .github/workflows/test-suite.yaml
  charts/lagoon-core/Chart.yaml
  charts/lagoon-core/templates/keycloak.deployment.yaml
Labels: needs-testing

#639 Set 1.28 as default for tests, also test 1.29
  .github/workflows/lint-test-matrix.yaml
  .github/workflows/lint-test.yaml
  .github/workflows/test-suite.yaml
Labels: needs-testing
