Repository uselagoon/lagoon-charts, pull requests merged in 2025-05, with the labels that each got.

#753 feat: tls support for lagoon-core broker
  .github/workflows/lint-test-matrix.yaml
  .github/workflows/lint-test.yaml
  Makefile
  broker-core-certificate-request.yaml
  charts/lagoon-build-deploy/Chart.yaml
  charts/lagoon-build-deploy/ci/linter-values.yaml
  charts/lagoon-build-deploy/templates/deployment.yaml
  charts/lagoon-build-deploy/templates/secret.yaml
  charts/lagoon-build-deploy/values.yaml
  charts/lagoon-core/Chart.yaml
  charts/lagoon-core/README.md
  charts/lagoon-core/broker-tls/README.md
  charts/lagoon-core/broker-tls/ca-config.json
  charts/lagoon-core/broker-tls/ca-csr.json
  charts/lagoon-core/broker-tls/server.json
  charts/lagoon-core/ci/linter-values.yaml
  charts/lagoon-core/templates/broker.secret.yaml
  charts/lagoon-core/templates/broker.service.yaml
  charts/lagoon-core/templates/broker.statefulset.yaml
  charts/lagoon-core/values.yaml
  charts/lagoon-logging/Chart.yaml
  charts/lagoon-logging/templates/logs-dispatcher.secret.yaml
  charts/lagoon-logging/templates/logs-dispatcher.source-lagoon.configmap.yaml
  charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml
  charts/lagoon-logging/values.yaml
  charts/lagoon-remote/Chart.yaml
  charts/lagoon-remote/ci/linter-values.yaml
  charts/lagoon-remote/templates/global-broker.secret.yaml
  charts/lagoon-remote/templates/insights-remote.deployment.yaml
  charts/lagoon-remote/templates/insights-remote.secrets.yaml
  charts/lagoon-remote/templates/storage-calculator.deployment.yaml
  charts/lagoon-remote/templates/storage-calculator.secret.yaml
  charts/lagoon-remote/values.yaml
Labels: next-release

#776 chore: update remote-controller to v0.23.0
  charts/lagoon-build-deploy/Chart.yaml
Labels: next-release

#777 chore: update lagoon-build-deploy subchart to v0.34.x
  charts/lagoon-remote/Chart.lock
  charts/lagoon-remote/Chart.yaml
  charts/lagoon-remote/templates/insights-remote.deployment.yaml
  charts/lagoon-remote/templates/storage-calculator.deployment.yaml
Labels: next-release

#773 Add startup probe and allow configuration of probes
  charts/lagoon-logs-concentrator/Chart.yaml
  charts/lagoon-logs-concentrator/templates/statefulset.yaml
  charts/lagoon-logs-concentrator/values.yaml
Labels: needs-testing

#788 fix: use correct variable for broker tls in insights-remote
  charts/lagoon-remote/Chart.yaml
  charts/lagoon-remote/templates/insights-remote.deployment.yaml
Labels: lagoon-remote
